### ISSUE TITLE
.qmd needs to contain R code

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/HW01-datalyticsintel#1]
Hi Antonio, 

The HTML rendered does not contain any information. This is because you're assignment is written as a .R script. If you would like help translating this to the .qmd file, please reach out. 

-Greg

**Comment by Gchism94** [comment]
Hey Antonio, 

Your new submission is closer to what I was asking for, however, the autograder will not work unless you have the assignment submitted via the hw-01.qmd file. This file already has the sections outlined. I also noticed that you did not use code chunks in the .Rmd document. This makes the code unreproducible in its current form. 

This [tutorial on using Quarto](https://quarto.org/docs/get-started/hello/rstudio.html) should be a helpful introduction to the core concepts of using Quarto documents, but also RMarkdown. 

Please reach out with questions and/or if you would like to meet to go through how to use .qmd documents. 
-Greg

**Comment by datalyticsintel** [comment]
Hi, so sorry. I never noticed this issue comments and was waiting for the feedback. I did get the slack messages and entered the code into the qmd files that Friday.
