### ISSUE TITLE
Homework 1 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/HW01-datalyticsintel#2]
Dear [datalyticsintel] -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

---

### Exercise 1: `[9 / 10 points]`

- Plot: `[6 / 6 points]`
- Narrative: `[3 / 4 points]`
- Feedback: I need more narrative into what the plots are showing you about the data. The serious and slight distributions are the same though, just a different fill color.  

### Exercise 2: `[8 / 20 points]`

a. `[6 / 8 points]`

  - Histogram: `[3 / 3]`
  - Boxplot: `[2 / 3]`
  - Narrative: `[1 / 2]`
  - Feedback: The y-axis on the boxplot should be removed because it doesn't actually show anything. Also, I need narrative into what the histogram plot is showing you. 

b. `[1 / 5 points]`

  - Boxplot: `[1 / 3]`
  - Narrative: `[0 / 2]`
  - Feedback: Your boxplot needs both an x and a y mapping inside the `aes()`. I also need narrative into what the plot is telling you. 

c. `[0 / 2 points]`

  - Feedback: This was not completed. 

d. `[1 / 5 points]`

  - Time series plot: `[1 / 3]`
  - Narrative: `[0 / 2]`
  - Feedback: A histogram is not a very effective way to show a time series, I suggest a line plot. You will also need to color the lines by `division`. Then, I will need narrative as to what the plot is telling you. 

### Exercise 3: `[5 / 20 points]`

a. `[1 / 2]`
  - Feedback: I am not sure I agree that the plot is showing the correlation effectively. 

b. `[2 / 2]`
  - Feedback: [Insert feedback here.]

c. `[2 / 16]` (2 points each)
  - Feedback: It seems like you struggled with this? Let's work to finish it together in a meeting or office hours. 
  
### Exercise 4: `[1 / 10 points]`

- Plot: `[1 / 6 points]`
- Narrative: `[0 / 4 points]`
- Feedback: It seems like you struggled with this? Let's work to finish it together in a meeting or office hours. 

### Exercise 5: `[5 / 20 points]`

Feedback: You were on the right track here. 

### Overall: `[17 / 20 points]`

- `[2 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
Feedback: I had to reproduce everything manually
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[3 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by datalyticsintel** [comment]
closing so HW2 isn't late
